version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: find_services
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: davidnine/find-services
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      HOST: db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      SECRET_KEY: 45ASDA

volumes:
  db_data: